# Generated by Django 6.0.7 on 2026-07-14 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_id', models.CharField(db_index=True, max_length=32, unique=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_name', models.CharField(max_length=255)),
                ('total_records', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_file_name', models.CharField(max_length=255)),
                ('serialno', models.CharField(max_length=50)),
                ('version', models.CharField(max_length=10)),
                ('account_id', models.CharField(max_length=50)),
                ('instance_id', models.CharField(max_length=50)),
                ('srcaddr', models.GenericIPAddressField(db_index=True)),
                ('dstaddr', models.GenericIPAddressField(db_index=True)),
                ('srcport', models.IntegerField()),
                ('dstport', models.IntegerField()),
                ('protocol', models.CharField(max_length=10)),
                ('packets', models.IntegerField()),
                ('bytes', models.BigIntegerField()),
                ('starttime', models.BigIntegerField()),
                ('endtime', models.BigIntegerField()),
                ('action', models.CharField(max_length=20)),
                ('log_status', models.CharField(max_length=20)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.dataset')),
            ],
        ),
    ]
